[theme]
bg = "#1E1E2E"
tab_num = "#DDB6F2"
tab_divider = "#C3BAC6"
bottombar_label = "#DDB6F2"
bottombar_text = "#B5E8E0"
bottombar_bg = "#302D41"
scrollbar = "#302D41"

hdg_1 = "#DDB6F2"
hdg_2 = "#DDB6F2"
hdg_3 = "#DDB6F2"
amfora_link = "#F28FAD"
foreign_link = "#F8BD96"
link_number = "#B5E8E0"
regular_text = "#C3BAC6"
quote_text = "#FAE3B0"
preformatted_text = "#F8BD96"
list_text = "#C3BAC6"

btn_bg = "#302D41"
btn_text = "#C3BAC6"

dl_choice_modal_bg = "#575268"
dl_choice_modal_text = "#C3BAC6"
dl_modal_bg = "#575268"
dl_modal_text = "#C3BAC6"
info_modal_bg = "#575268"
info_modal_text = "#C3BAC6"
error_modal_bg = "#F28FAD"
error_modal_text = "#C3BAC6"
yesno_modal_bg = "#575268"
yesno_modal_text = "#C3BAC6"
tofu_modal_bg = "#575268"
tofu_modal_text = "#C3BAC6"
subscription_modal_bg = "#575268"
subscription_modal_text = "#C3BAC6"

input_modal_bg = "#575268"
input_modal_text = "#C3BAC6"
input_modal_field_bg = "#302D41"
input_modal_field_text = "#C3BAC6"

bkmk_modal_bg = "#575268"
bkmk_modal_text = "#C3BAC6"
bkmk_modal_label = "#C3BAC6"
bkmk_modal_field_bg = "#302D41"
bkmk_modal_field_text = "#C3BAC6"

