[theme]
bg = "#303446"
tab_num = "#ca9ee6"
tab_divider = "#a5adce"
bottombar_text = "#81c8be"
bottombar_bg = "#51576d"
scrollbar = "#51576d"

hdg_1 = "#ca9ee6"
hdg_2 = "#ca9ee6"
hdg_3 = "#ca9ee6"
amfora_link = "#e78284"
foreign_link = "#ef9f76"
link_number = "#81c8be"
regular_text = "#c6d0f5"
quote_text = "#e5c890"
preformatted_text = "#ef9f76"
list_text = "#c6d0f5"

btn_bg = "#51576d"
btn_text = "#c6d0f5"

dl_choice_modal_bg = "#51576d"
dl_choice_modal_text = "#c6d0f5"
dl_modal_bg = "#51576d"
dl_modal_text = "#c6d0f5"
info_modal_bg = "#51576d"
info_modal_text = "#c6d0f5"
error_modal_bg = "#e78284"
error_modal_text = "#292c3c"
yesno_modal_bg = "#51576d"
yesno_modal_text = "#c6d0f5"
tofu_modal_bg = "#51576d"
tofu_modal_text = "#c6d0f5"
subscription_modal_bg = "#51576d"
subscription_modal_text = "#c6d0f5"

input_modal_bg = "#51576d"
input_modal_text = "#c6d0f5"
input_modal_field_bg = "#414559"
input_modal_field_text = "#c6d0f5"

bkmk_modal_bg = "#51576d"
bkmk_modal_text = "#c6d0f5"
bkmk_modal_label = "#c6d0f5"
bkmk_modal_field_bg = "#414559"
bkmk_modal_field_text = "#c6d0f5"

