[theme]
bg = "#eff1f5"
tab_num = "#8839ef"
tab_divider = "#6c6f85"
bottombar_text = "#179299"
bottombar_bg = "#bcc0cc"
scrollbar = "#bcc0cc"

hdg_1 = "#8839ef"
hdg_2 = "#8839ef"
hdg_3 = "#8839ef"
amfora_link = "#d20f39"
foreign_link = "#fe640b"
link_number = "#179299"
regular_text = "#4c4f69"
quote_text = "#df8e1d"
preformatted_text = "#fe640b"
list_text = "#4c4f69"

btn_bg = "#bcc0cc"
btn_text = "#4c4f69"

dl_choice_modal_bg = "#bcc0cc"
dl_choice_modal_text = "#4c4f69"
dl_modal_bg = "#bcc0cc"
dl_modal_text = "#4c4f69"
info_modal_bg = "#bcc0cc"
info_modal_text = "#4c4f69"
error_modal_bg = "#d20f39"
error_modal_text = "#e6e9ef"
yesno_modal_bg = "#bcc0cc"
yesno_modal_text = "#4c4f69"
tofu_modal_bg = "#bcc0cc"
tofu_modal_text = "#4c4f69"
subscription_modal_bg = "#bcc0cc"
subscription_modal_text = "#4c4f69"

input_modal_bg = "#bcc0cc"
input_modal_text = "#4c4f69"
input_modal_field_bg = "#ccd0da"
input_modal_field_text = "#4c4f69"

bkmk_modal_bg = "#bcc0cc"
bkmk_modal_text = "#4c4f69"
bkmk_modal_label = "#4c4f69"
bkmk_modal_field_bg = "#ccd0da"
bkmk_modal_field_text = "#4c4f69"

