[theme]
bg = "#24273a"
tab_num = "#c6a0f6"
tab_divider = "#a5adcb"
bottombar_text = "#8bd5ca"
bottombar_bg = "#494d64"
scrollbar = "#494d64"

hdg_1 = "#c6a0f6"
hdg_2 = "#c6a0f6"
hdg_3 = "#c6a0f6"
amfora_link = "#ed8796"
foreign_link = "#f5a97f"
link_number = "#8bd5ca"
regular_text = "#cad3f5"
quote_text = "#eed49f"
preformatted_text = "#f5a97f"
list_text = "#cad3f5"

btn_bg = "#494d64"
btn_text = "#cad3f5"

dl_choice_modal_bg = "#494d64"
dl_choice_modal_text = "#cad3f5"
dl_modal_bg = "#494d64"
dl_modal_text = "#cad3f5"
info_modal_bg = "#494d64"
info_modal_text = "#cad3f5"
error_modal_bg = "#ed8796"
error_modal_text = "#1e2030"
yesno_modal_bg = "#494d64"
yesno_modal_text = "#cad3f5"
tofu_modal_bg = "#494d64"
tofu_modal_text = "#cad3f5"
subscription_modal_bg = "#494d64"
subscription_modal_text = "#cad3f5"

input_modal_bg = "#494d64"
input_modal_text = "#cad3f5"
input_modal_field_bg = "#363a4f"
input_modal_field_text = "#cad3f5"

bkmk_modal_bg = "#494d64"
bkmk_modal_text = "#cad3f5"
bkmk_modal_label = "#cad3f5"
bkmk_modal_field_bg = "#363a4f"
bkmk_modal_field_text = "#cad3f5"