[theme]
bg = "#1e1e2e"
tab_num = "#cba6f7"
tab_divider = "#a6adc8"
bottombar_text = "#94e2d5"
bottombar_bg = "#45475a"
scrollbar = "#45475a"

hdg_1 = "#cba6f7"
hdg_2 = "#cba6f7"
hdg_3 = "#cba6f7"
amfora_link = "#f38ba8"
foreign_link = "#fab387"
link_number = "#94e2d5"
regular_text = "#cdd6f4"
quote_text = "#f9e2af"
preformatted_text = "#fab387"
list_text = "#cdd6f4"

btn_bg = "#45475a"
btn_text = "#cdd6f4"

dl_choice_modal_bg = "#45475a"
dl_choice_modal_text = "#cdd6f4"
dl_modal_bg = "#45475a"
dl_modal_text = "#cdd6f4"
info_modal_bg = "#45475a"
info_modal_text = "#cdd6f4"
error_modal_bg = "#f38ba8"
error_modal_text = "#181825"
yesno_modal_bg = "#45475a"
yesno_modal_text = "#cdd6f4"
tofu_modal_bg = "#45475a"
tofu_modal_text = "#cdd6f4"
subscription_modal_bg = "#45475a"
subscription_modal_text = "#cdd6f4"

input_modal_bg = "#45475a"
input_modal_text = "#cdd6f4"
input_modal_field_bg = "#313244"
input_modal_field_text = "#cdd6f4"

bkmk_modal_bg = "#45475a"
bkmk_modal_text = "#cdd6f4"
bkmk_modal_label = "#cdd6f4"
bkmk_modal_field_bg = "#313244"
bkmk_modal_field_text = "#cdd6f4"